
language: node_js
node_js:
  - "v12.22.3"
sudo: required
before_install:
  - echo "Before install"
install:
  - echo "Install"
  - npm install --save bufferutil@3 ws@1
  - npm install -g jest
script:
  - ./test/test.sh
  # TODO: Docker build and upload