dist: jammy
sudo: required
arch:
  - amd64
  - arm64
  - armv7
env:
  global:
    - DOCKER_REPO=sthinds/sthinds.io
services:
  - docker
  # for testing
  - mongodb
  - redis-server
cache:
  directories:
    - docker

# step definitions
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
before_install:
  - sudo apt-get update
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker start
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  - docker load -i docker/images.tar || true
# install:
before_script:
  - mongo test --eval 'db.createUser({user:"test",pwd:"test",roles:["readWrite"]});'
script:
  # TODO: pass in --env variables here
  #       - build base/build image first (no env variables)
  #       - build server (with env)
  #       - build test (with env)

  - docker build . --tag $DOCKER_REPO:$TRAVIS_CPU_ARCH --target deploy

  - docker build . --target test --tag $DOCKER_REPO:test
  - docker run --network host $DOCKER_REPO:test
  - docker push $DOCKER_REPO:$TRAVIS_CPU_ARCH