dist: jammy
sudo: required
arch:
  - amd64
  - arm64
  - armv7
env:
  global:
    - DOCKER_REPO=sthinds/sthinds.io
services:
    - docker
before_install:
  - sudo apt-get update
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
# install:
script:
  # TODO: pass in --env variables here
  #       - build base/build image first (no env variables)
  #       - build server (with env)
  #       - build test (with env)
  - docker build --tag $DOCKER_REPO \
                        --target deploy \
                        --push .
  - docker build --target test .