
language: node_js
node_js:
  - "v12.22.3"
sudo: required
before_install:
  - echo "Before install"
install:
  - echo "Install"
  - npm install -g jest ts-jest typescript@latest react-scripts babel-jest@26.6.0
  - npm install -D jest ts-jest typescript@latest
  - cd server
  - npm install
  - cd ../client
  - npm install
  - cd ..
  - ls node_modules
  - ls client/node_modules
  - ls server/node_modules
script:
  - ./test/test.sh
  # TODO: Docker build and upload