dist: jammy
sudo: required
env:
  global:
    - DOCKER_REPO=sthinds/sthinds.io
    - ARCHITECTURE_TARGETS=linux/arm/v7,linux/arm64,linux/amd64
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu `lsb_release -cs` test"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - curl --silent -L \
    "https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo service docker start
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  # TODO: what is this? necessary?
  - docker buildx create --name xbuilder --use
script:
  # TODO: pass in --env variables here
  #       - build base/build image first (no env variables)
  #       - build server (with env)
  #       - build test (with env)
  - docker buildx build --progress plain \
                        --platform=$ARCHITECTURE_TARGETS \
                        --tag $DOCKER_REPO \
                        --target deploy \
                        --push .
  - docker buildx build --progress plain \
                        --platform=$ARCHITECTURE_TARGETS \
                        --target test