
language: node_js
node_js:
  - "v12.22.3"
sudo: required
before_install:
  - echo "Before install"
install:
  - echo "Install"
  - npm install -g jest ts-jest typescript@latest
  - npm install -D jest typescript@latest
script:
  - ./test/test.sh
  # TODO: Docker build and upload