
language: node_js
node_js:
  - "v12.22.3"
sudo: required
before_install:
  - echo "Before install"
install:
  - echo "Install"
  - npm install -g jest ts-jest typescript@latest react-scripts
  - npm install -D jest ts-jest typescript@latest
  - cd server
  - npm install
  - cd ../client
  - npm install
  - cd ..
script:
  - ./test/test.sh
  # TODO: Docker build and upload