version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /tmp/mongodb:/data/db
    ports:
      - 0.0.0.0:27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=test,prod,dev
    command: mongod
    privileged: true
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - /tmp/redis/redis-data:/var/lib/redis
      - /tmp/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
